### ISSUE TITLE
Tracking Issue: video headers implementation status

### ISSUE THREAD

**Issue by LunarLambda** [LunarLambda/libseven#1]
# Implementation status (as of https://github.com/LunarLambda/libseven/commit/00f7f12d601eecdb607cb36ab7d49fdf64b3bc2c)

## `<seven/hw/video.h>`
- [x] Display control (DISPCNT, DISPSTAT, VCOUNT)
- [x] Background control (BGxCNT)
- [x] Memory maps (Palettes)  

## `<seven/video/bg_affine.h>`
- [x] Affine background registers
- [ ] Affine transform functions?

## `<seven/video/bg_bitmap.h>`
- [x] Memory maps (Framebuffers)
- [x] Buffer swapping / 'page flipping' function
- [ ] Drawing functions? 
 
## `<seven/video/bg_regular.h>`
- [x] Definitions
- [ ] Functions (tilewise copy, large map tile loading?)

## `<seven/video/blend.h>`
- [x] Registers
- [ ] Helper macros
- [ ] Functions  

## `<seven/video/color.h>`
- [x] Basic RGB5 / RGB8 macros, color bitfields
- [ ] Color math/effect functions
- [ ] Predefined colors

## `<seven/video/mosaic.h>`
- [x] Registers, bitfields

## `<seven/video/object.h>` (TODO)
- [ ] Definitions
- [ ] Functions (movement, etc?)
- [ ] Affine definitions
- [ ] Affine functions

## `<seven/video/palette.h>` (TODO)
- [ ] Palette effect functions

## `<seven/video/scroll.h>`
- [x] Scroll registers (BGxHOFS, BGxVOFS)
- [ ] Scroll functions (i.e. to handle write-only nature?)

## `<seven/video/window.h>`
- [x] Registers
- [ ] Functions (Rectangle setting?)

**Comment by LunarLambda** [comment]
2022-02-01: Resolved open questions, updated header naming

**Comment by LunarLambda** [comment]
Updated and rename the issue, since video header organisation is now basically figured out.
